### ISSUE TITLE
Cannot use with kwallet any more

### ISSUE THREAD

**Issue by protist** [jaraco/keyring#235]
I just upgraded from keyring 9.2.1 to 9.3, and I can no longer access my kwallet passwords. It worked fine in 9.1, and perhaps 9.2.1. I'm not really sure what I'm doing, but I followed a few hints from other issues here.

```
$ python
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.get_password("mbsync","foo@bar.com")
>>> keyring.get_keyring()
<keyring.backends.SecretService.Keyring object at 0x7f32a1719080>
>>> import keyring.backends.kwallet
>>> keyring.get_password("mbsync","foo@bar.com")
>>> print(keyring.backends.kwallet.Keyring.priority)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keyring.backends.kwallet' has no attribute 'Keyring'
```

I tried using keyring directly from the shell, but I'm not really sure how to specify the backend (and the README is a bit lacking).

```
$ keyring get mbsync foo@bar.com
$ keyring -b kwallet get mbsync foo@bar.com
Usage: keyring [get|set|del] SERVICE USERNAME

keyring: error: Unable to load specified keyring: Empty module name
$ keyring -b keyring.backends.kwallet get mbsync foo@bar.com
Usage: keyring [get|set|del] SERVICE USERNAME

keyring: error: Unable to load specified keyring: module 'keyring.backends.kwallet' has no attribute 'priority'
$ keyring -b keyring.backends.kwallet.Keyring get mbsync foo@bar.com
Usage: keyring [get|set|del] SERVICE USERNAME

keyring: error: Unable to load specified keyring: module 'keyring.backends.kwallet' has no attribute 'Keyring'
```

Finally, I tried creating `~/.local/share/python_keyring/keyringrc.cfg` with the following.

```
[backend]
default-keyring = keyring.backends.kwallet.Keyring
```

However, this still failed.

```
$ keyring get mbsync foo@bar.com
Traceback (most recent call last):
  File "/usr/bin/keyring", line 9, in <module>
    load_entry_point('keyring==9.3', 'console_scripts', 'keyring')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 149, in <module>
    init_backend()
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 68, in init_backend
    load_config()
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 138, in load_config
    return load_keyring(keyring_name)
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 106, in load_keyring
    class_ = _load_keyring_class(keyring_name)
  File "/usr/lib/python3.5/site-packages/keyring/core.py", line 98, in _load_keyring_class
    return getattr(module, class_name)
AttributeError: module 'keyring.backends.kwallet' has no attribute 'Keyring'
```

I just tested downgrading to 9.1 and 9.2.1, but neither actually work. Perhaps some of the dependencies have changed? I couldn't see anything obvious. I'm using Arch Linux.

**Comment by protist** [comment]
Oh, it looks like it's defaulting to the gnome keyring now. I'm running KDE Plasma but also have gnome-keyring installed. In a previous version, keyring would automatically select the kwallet keyring, but now it seems to select gnome's instead.

**Comment by jaraco** [comment]
Does the [history](https://pythonhosted.org/keyring/history.html) provide any hint as to what might be different?

**Comment by mitya57** [comment]
> ``` python
> print(keyring.backends.kwallet.Keyring.priority)
> ```

You need to change `Keyring` to `DBusKeyring`.

> ```
> [backend]
> default-keyring = keyring.backends.kwallet.Keyring
> ```

The same here.

**Comment by protist** [comment]
> Does the history provide any hint as to what might be different?

Unfortunately nothing directly relating to kwallet that I can see. The only change in 9.3 listed is

> Pull Request #226: In SecretService backend, unlock individual entries.

I'm not sure how that relates.

> You need to change Keyring to DBusKeyring.

Thanks, changing that string in `~/.local/share/python_keyring/keyringrc.cfg` partially fixed it for me. Unfortunately it's now returning the password in a different format to before.

```
dbus.String('<PASSWORD>')
```

Unless there is a single quote in it, then it's

```
dbus.String("<PASSWORD>")
```

If there are both, it's escaped. e.g. for `a'b"c`

```
dbus.String('a\'b"c')
```

That's not really useable in a general case.

**Comment by mitya57** [comment]
I think it's a bug we need to fix.

@jaraco What's the desired output format for passwords? Is it bytestring (`bytes` for Python 3 and `str` on Python 2), or `str` on both Pythons?

I just noticed that SecretStorage returns the password as `bytearray`, I think I'll change that to `bytes`.

**Comment by jaraco** [comment]
Good question. I think the keyring protocol should accept text (str on Python 3 and unicode on Python 2) and return text. I'm pretty sure the tests guarantee this expectation. If they do not, we should update them to do so.

I'm not sure what a dbus.String is, but it does appear to be a wrapper around a text string, and the escaping looks exactly what I'd expect from a repr of a native string on any Python:

```
>>> """a'b"c"""
'a\'b"c'
>>> print(_)
a'b"c
```

So it's not clear to me from the post that there's a bug there.

@protist, can you elaborate a bit more on what's unexpected and also what you would expect instead?

**Comment by mitya57** [comment]
Alright, I for some reason thought that the passwords should be byte strings, but that's apparently not true.

`dbus.String` is indeed a subclass of `str`, though I would still fix the Kwallet backend to return real strings (so that apps checking for `type(password) == str` won't fail).

**Comment by protist** [comment]
@jaraco When I don't change the configuration file, keyring pulls from Gnome Keyring, which gives me raw, unescaped text. Previous versions of keyring did the same thing with kwallet.

I'm using keyring to pull passwords for programs like mbsync and vdirsyncer, so raw, unescaped passwords is perfect, and consistent with the behaviour with Gnome Keyring.

**Comment by mitya57** [comment]
I agree with @protist, all backends should be consistent in what results they return. Who knows, maybe applications call `repr()` on passwords or check the value of `type(password)`. I fixed this in Git now.

**Comment by protist** [comment]
Thanks for the quick fix, @mitya57. Just to confirm, is the desired behaviour to select kwallet manually with the config file at `~/.local/share/python_keyring/keyringrc.cfg`? Just because this behaviour has changed for me too. Cheers.

**Comment by mitya57** [comment]
Yes. If there's a Secret Service implementation (like gnome-keyring) then it's preferred because that is a standard.

If you don't want this, disable the gnome-keyring auto start-up.
